### PR TITLE
fix: Cypress executor logs broken

### LINKED ISSUE #533: Invalid logs watching for Cypress runner
**Describe the bug**
When running Cypress based test e.g. 

```
➜  testkube git:(main) s start dashboard-test -f

████████ ███████ ███████ ████████ ██   ██ ██    ██ ██████  ███████
   ██    ██      ██         ██    ██  ██  ██    ██ ██   ██ ██
   ██    █████   ███████    ██    █████   ██    ██ ██████  █████
   ██    ██           ██    ██    ██  ██  ██    ██ ██   ██ ██
   ██    ███████ ███████    ██    ██   ██  ██████  ██████  ███████
                                           /tɛst kjub/ by Kubeshop


Type          : cypress/project
Name          : dashboard-test
Execution ID  : 61973909c369edb510cefbfe
Execution name: loosely-whole-ocelot

Script execution started
Use following command to get script execution details:
$ kubectl testkube scripts execution 61973909c369edb510cefbfe

or watch script execution until complete:
$ kubectl testkube scripts watch 61973909c369edb510cefbfe


Getting pod logs.                        # <------------------------------- HERE IT STARTS 
running test script [61973909c369edb510cefbfe]
# <-------------------------------------- ONLY ONE LINE IS PASSED 


Use following command to get script execution details:
$ kubectl testkube scripts execution 61973909c369edb510cefbfe

or watch script execution until complete:
$ kubectl testkube scripts watch 61973909c369edb510cefbfe
```

**Expected behavior**

**Version / Cluster**
- v0.6.16 
- Only on GKE testkube-dev - works on bare metal

### LINKED ISSUE #560: Specified bucket does not exists
**Describe the bug**

I am just getting started with testkube and trying it locally on a windows minikube but have run into the following error when I try the cypress example:  

``` 

(error: api/list-artifacts returned error: api server problem: The specified bucket does not exist;
resp error:an error on the server ("unknown") has prevented the request from succeeding (get services testkube-api-server:8088))

```

Any thoughts as to what might cause this?

Error from discord passed by ehawk61 user

### PR DESCRIPTION
**Pull request by exu**
## Pull request description 

- added download all artifacts by default download is now download-one
- fix for Cypress logs on GKE 
- simplified passing/closing channel to logs stream
- simplified reading streams
- kubectl plugin UI fixes
- closes #533 
- closes #560 

## Checklist (choose whats happened)

- [ ] breaking change! (describe)
- [x] tested locally
- [ ] tested on cluster
- [ ] added new dependencies
- [ ] updated the docs
- [ ] added a test

## Breaking changes

-

## Changes

-

## Fixes

-

### CODE REVIEW

File: cmd/kubectl-testkube/commands/artifacts.go [hunk 1]
```diff
@@ -67,9 +69,9 @@ func NewListArtifactsCmd() *cobra.Command {
 	return cmd
 }
 
-func NewDownloadArtifactsCmd() *cobra.Command {
+func NewDownloadSingleArtifactsCmd() *cobra.Command {
 	cmd := &cobra.Command{
-		Use:   "download",
+		Use:   "download-one",
```
Comment (jasmingacic) [inline cmd/kubectl-testkube/commands/artifacts.go:74]: shouldn't we handle this with flags like "download --all" instead of replacing it with "download-one" subcommand?

File: cmd/kubectl-testkube/commands/artifacts.go [hunk 2]
```diff
@@ -108,3 +110,32 @@ func NewDownloadArtifactsCmd() *cobra.Command {
 	// output renderer flags
 	return cmd
 }
+
+func NewDownloadAllArtifactsCmd() *cobra.Command {
```
Comment (jasmingacic) [inline cmd/kubectl-testkube/commands/artifacts.go:114]: The same as above. Why not handle it with flags instead of separate commands?

File: cmd/kubectl-testkube/commands/artifacts.go (hunk 1 above)
Comment (exu) [reply cmd/kubectl-testkube/commands/artifacts.go:74]: don't think so - branching code is worse than splitting it

Comment (exu) [reply cmd/kubectl-testkube/commands/artifacts.go:74]: we'll see what users say but I think that most use cases should be for downloading all artifacts - passing those names and escaping them when you'll have spaces will be pain in the ass.

**Review by nicufk — APPROVED** [review]
LGTM

**Review by jasmingacic — APPROVED** [review]
