### PR TITLE
fix: added flags validation into create test

### LINKED ISSUE #1319: Validate test creating command
**Describe the enhancement you'd like to see**

## Problem and debugging

When creating a Cypress test, I had to pass a git repository url with the `--git-uri` option.

I didn't however think that I needed to add `--git-branch` (as I suspected the default or main would be used). I also didn't think `--git-path` should be passed, because my project was in the root. 

The result has been a very complex debugging of the issue, specially in the case of omitting `--git-branch` where the only way it failed was 

```
kubectl testkube watch execution 625e814c814c4805514aa6c1

execution is already finished
```

and debugging the pod, the error was not clear at all 
```
➜  kubectl describe pods 625e814c814c4805514aa6c1-j25bp
Name:         625e814c814c4805514aa6c1-j25bp
Namespace:    testkube
Priority:     0
...
Init Containers:
  625e814c814c4805514aa6c1-init:
    Container ID:  docker://c6877afdc73464a61de823d20a89c4fb47423a8100177b80bdc546a43b8791ff
...
State:          Terminated
      Reason:       ContainerStatusUnknown
      Message:      The container could not be located when the pod was terminated
      Exit Code:    137
...
Events:
  Type    Reason     Age   From               Message
  ----    ------     ----  ----               -------
  Normal  Scheduled  84s   default-scheduler  Successfully assigned testkube/625e814c814c4805514aa6c1-j25bp to minikube
  Normal  Pulling    83s   kubelet            Pulling image "kubeshop/testkube-executor-init:0.7.7"
  Normal  Pulled     81s   kubelet            Successfully pulled image "kubeshop/testkube-executor-init:0.7.7" in 2.806589709s
  Normal  Created    81s   kubelet            Created container 625e814c814c4805514aa6c1-init
  Normal  Started    81s   kubelet            Started container 625e814c814c4805514aa6c1-init
```

## Proposed solution 

Depending on the executor, validate the options that need to be passed to create the test, and report clear error messages before running.

### PR DESCRIPTION
**Pull request by exu**
## Pull request description 

closes #1319

## Checklist (choose whats happened)

- [ ] breaking change! (describe)
- [ ] tested locally
- [ ] tested on cluster
- [ ] added new dependencies
- [ ] updated the docs
- [ ] added a test

## Breaking changes

-

## Changes

-

## Fixes

-

### CODE REVIEW

File: cmd/kubectl-testkube/commands/tests/create.go [hunk 1]
```diff
@@ -84,6 +90,41 @@ func NewCreateTestsCmd() *cobra.Command {
...
+	gitUri := cmd.Flag("git-uri").Value.String()
+	gitBranch := cmd.Flag("git-branch").Value.String()
+	gitPath := cmd.Flag("git-path").Value.String()
+	gitUsername := cmd.Flag("git-username").Value.String()
+	gitToken := cmd.Flag("git-token").Value.String()
+
+	file := cmd.Flag("file").Value.String()
+	uri := cmd.Flag("uri").Value.String()
+
+	hasGitParams := gitBranch != "" || gitPath != "" || gitUri != "" || gitToken != "" || gitUsername != ""
```
Comment (vsukhin) [inline cmd/kubectl-testkube/commands/tests/create.go:103]: It will work for now, but I would be created a set of methods for Test model

**Review by vsukhin — APPROVED** [review]
