### PR TITLE
fix: user friendly oss feature error messages

### LINKED ISSUE #5629: Show user friendly error message about disabled OSS feature in cli
**Describe the enhancement you'd like to see**
Show  user friendly error message about disabled OSS feature in cli when execute test workflow

### PR DESCRIPTION
**Pull request by vsukhin**
## Pull request description 

Fix #5629 

## Checklist (choose whats happened)

- [ ] breaking change! (describe)
- [x] tested locally
- [x] tested on cluster
- [ ] added new dependencies
- [ ] updated the docs
- [ ] added a test

## Breaking changes

-

## Changes

-

## Fixes

-

### CODE REVIEW

File: cmd/kubectl-testkube/commands/testworkflows/run.go [hunk 1]
```diff
@@ -69,6 +70,19 @@ func NewRunTestWorkflowCmd() *cobra.Command {
 				Config:          config,
 				DisableWebhooks: disableWebhooks,
 			})
+			if err != nil {
+				// User friendly Open Source operation error
+				errs := []error{constants.ErrOpenSourceExecuteOperationIsNotAvailable,
+					constants.ErrOpenSourceParallelOperationIsNotAvailable,
+					constants.ErrOpenSourceServicesOperationIsNotAvailable}
+				for _, e := range errs {
+					if strings.Contains(err.Error(), e.Error()) {
```
Comment (rangoo94) [inline cmd/kubectl-testkube/commands/testworkflows/run.go:79]: Maybe just `Contains` on the `constants.OpenSourceOperationErrorMessage`?

Comment (vsukhin) [reply cmd/kubectl-testkube/commands/testworkflows/run.go]: anyway, changed to parsing, should be more universal
