### PR TITLE
fix: more cypress statuses

### LINKED ISSUE #4058: Unable to Retrieve Skipped/Pending Test Results via REST API after Execution
**Describe the bug**
Dear Testkube Team,

I hope this message finds you well. I would like to bring to your attention a bug I encountered while working with Testkube.

**Issue**:
Currently, there seems to be a limitation in retrieving skipped and pending test results via the REST API after test execution. When attempting to fetch the test case results through the API, only passed and failed results are being returned. This poses a challenge as it prevents users from accessing crucial information about skipped and pending test cases.

**To Reproduce**
1. Executed a test containing skipped and pending test cases using Testkube.
2. config
```
describe('Example to Demostrate the use of skip in cypress', () => {
    before(() => {
        cy.visit('https://wikipedia.org')
    })

    it.skip('Validate Page Title', () => {
        cy.title().should('eq', 'Wikipedia')
    })

    it('Search for Google Wiki Page', () => {
        cy.get('#searchInput').type('google')
        cy.get('button[type="submit"]').click()
    })

    it.skip('Validate Google Wiki Page has opened', () => {
        cy.get('h1#firstHeading').contains('Google')
        cy.title().should('eq', 'Google - Wikipedia')
    })
})
```
3. Execution results in the testkube
┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        3                                                                                │
  │ Passing:      1                                                                                │
  │ Failing:      0                                                                                │
  │ Pending:      1                                                                                │
  │ Skipped:      1                                                                                │
  │ Screenshots:  0                                                                                │
  │ Video:        true                                                                             │
  │ Duration:     39 seconds                                                                       │
  │ Spec Ran:     skipped.cy.js                                                                    │
  └────────────────────────────────────────
4. Execution results using restapi
api: http://localhost:8088/v1/executions/{execution_id}
results: 
```
"steps": [
      {
        "name": "Example to Demostrate the use of skip in cypress - Example to Demostrate the use of skip in cypress Search for Google Wiki Page",
        "duration": "28.704s",
        "status": "passed"
      }
    ]
```
Observed that only passed and failed results are returned, while skipped and pending results are missing.

**Expected behavior**
I kindly request that the Testkube platform be enhanced to include support for retrieving all test case results, including those that are marked as skipped or pending, through the REST API. This would greatly improve the usability and effectiveness of the platform, as it would provide a comprehensive overview of the test execution status.

**Version / Cluster**
- Which testkube version? 
- What Kubernetes cluster? (e.g. GKE, EKS, Openshift etc, local KinD, local Minikube)
- What Kubernetes version?

**Screenshots**
If applicable, add CLI commands/output to help explain your problem.
 
**Additional context**

### PR DESCRIPTION
**Pull request by vsukhin**
## Pull request description 

Fix #4058 

## Checklist (choose whats happened)

- [ ] breaking change! (describe)
- [ ] tested locally
- [ ] tested on cluster
- [ ] added new dependencies
- [ ] updated the docs
- [ ] added a test

## Breaking changes

-

## Changes

-

## Fixes

-

### CODE REVIEW

File: contrib/executor/cypress/pkg/runner/cypress.go [hunk 1]
```diff
@@ -265,6 +265,10 @@ func MapStatus(in junit.Status) (out string) {
 	switch string(in) {
 	case "passed":
 		return string(testkube.PASSED_ExecutionStatus)
+	case "pended":
```
Comment (vLia) [inline contrib/executor/cypress/pkg/runner/cypress.go:268]: should this be pending?
```suggestion
	case "pending":
```

**Review by vLia — APPROVED** [review]
looks good, just one question

File: contrib/executor/cypress/pkg/runner/cypress.go (hunk 1 above)
Comment (vsukhin) [reply contrib/executor/cypress/pkg/runner/cypress.go:268]: good question, checking with user)

**Review by nicufk — APPROVED** [review]
