### PR TITLE
fix: use registry for inspection

### LINKED ISSUE #5214: Docker image inspection error while using private registry
**Describe the bug**
I use a private ECR registry storing all images - testkube related and custom containers executors. 

Private registry is set using global values attached to chart:
```
global:
  imageRegistry: "***************.dkr.ecr.eu-central-1.amazonaws.com"
```

Testkube installation works as expected and tests are executed using images from correct registry but before pod with test starts I got error in API which block execution for 60 seconds until timeout in InspectDockerImage which, as it looks in error message, still uses default registry:

```
  "level": "error",
  "ts": 1710848355.6584322,
  "caller": "containerexecutor/tmpl.go:296",
  "msg": "Docker image inspection error",
  "error": "could not start process with command: skopeo, exited with code:1  error: exit status 1,output: time=\"2024-03-19T11:39:15Z\" level=fatal msg=\"Error parsing image name \\\"docker://tests-boiler-plate-qa-testkube-executor:0.1.1\\\": pinging container registry registry-1.docker.io: Get \\\"https://registry-1.docker.io/v2/\\\": dial tcp 54.198.86.24:443: i/o timeout\"\n",
  "stacktrace": "github.com/kubeshop/testkube/pkg/executor/containerexecutor.NewJobOptions,
    /home/runner/work/testkube/testkube/pkg/executor/containerexecutor/tmpl.go:296
    github.com/kubeshop/testkube/pkg/executor/containerexecutor.(*ContainerExecutor).createJob
    /home/runner/work/testkube/testkube/pkg/executor/containerexecutor/containerexecutor.go:281
    github.com/kubeshop/testkube/pkg/executor/containerexecutor.(*ContainerExecutor).Execute
    /home/runner/work/testkube/testkube/pkg/executor/containerexecutor/containerexecutor.go:239
    github.com/kubeshop/testkube/pkg/scheduler.(*Scheduler).startTestExecution
    /home/runner/work/testkube/testkube/pkg/scheduler/test_scheduler.go:124
    github.com/kubeshop/testkube/pkg/scheduler.(*Scheduler).executeTest
    /home/runner/work/testkube/testkube/pkg/scheduler/test_scheduler.go:101
    github.com/kubeshop/testkube/pkg/workerpool.Request[...].execute
    /home/runner/work/testkube/testkube/pkg/workerpool/service.go:43
    github.com/kubeshop/testkube/pkg/workerpool.worker[...]
    /home/runner/work/testkube/testkube/pkg/workerpool/service.go:108"
}
``` 

May that be a reason of some misconfiguration, any workaround or fix available?

**Version / Cluster**
- Which testkube version? 1.16.25
- What Kubernetes cluster? EKS
- What Kubernetes version? v1.29.1-eks-508b6b3

### PR DESCRIPTION
**Pull request by vsukhin**
## Pull request description 

fix #5214

## Checklist (choose whats happened)

- [ ] breaking change! (describe)
- [ ] tested locally
- [ ] tested on cluster
- [ ] added new dependencies
- [ ] updated the docs
- [ ] added a test

## Breaking changes

-

## Changes

-

## Fixes

-

### CODE REVIEW

File: pkg/skopeo/client.go [hunk 1]
```diff
@@ -89,7 +89,12 @@ func (c *client) Inspect(image string) (*DockerImage, error) {
 		args = append(args, "--creds", c.dockerAuthConfigs[i].Username+":"+c.dockerAuthConfigs[i].Password)
 	}
 
-	args = append(args, "--config", "docker://"+image)
+	config := "docker://" + image
+	if registry != "" {
+		config = registry + "/" + image
```
Comment (rangoo94) [inline pkg/skopeo/client.go:94]: It may happen that `image` has already a registry, like `ghcr.io/some/image` - probably it should ignore `registry` variable then?

Comment (vsukhin) [reply pkg/skopeo/client.go:94]: i guess, they should be stored in private registry as `ghcr.io/hlesey/busybox` in this case, right @ypoplavs ?

Comment (ypoplavs) [reply pkg/skopeo/client.go:94]: The path for private registry is: `LOCATION-docker.pkg.dev/PROJECT-ID/REPOSITORY/IMAGE`

Comment (vsukhin) [reply pkg/skopeo/client.go:94]: Test by @ypoplavs 
```yes, I pushed a test image to the registry in testkube project, the path is:
us-east1-docker.pkg.dev/testkube-328312/test/quickstart-image
```
