### PR TITLE
feat: duration for testexecutions and for executions + small fixes

### LINKED ISSUE #781: Brew formula misconfiguration
**Describe the bug**
Brew formula has the incorrect name and doesn't work as described in the docs.

**To Reproduce**
1. Run ' 
image

**Expected behavior**
Instead the command that works is the following, where testkube is repeated twice.
image

### LINKED ISSUE #784: Add duration to executions and test-executions resources

### LINKED ISSUE #785: Add global debug logging for api endpoints

### PR DESCRIPTION
**Pull request by exu**
## Pull request description 

As api client I want to have duration calculated on backend.

closes #781 
closes #784
closes #785

## Checklist (choose whats happened)

- [ ] breaking change! (describe)
- [x] tested locally
- [ ] tested on cluster
- [ ] added new dependencies
- [ ] updated the docs
- [ ] added a test

## Breaking changes

-

## Changes

-

## Fixes

-

### CODE REVIEW

File: internal/app/api/v1/tests.go [hunk 1]
```diff
@@ -220,7 +227,7 @@ func (s TestKubeAPI) executeTestStep(ctx context.Context, testName string, step
 	case testkube.TestStepTypeExecuteScript:
 		executeScriptStep := step.Execute
 		options, err := s.GetExecuteOptions(executeScriptStep.Namespace, executeScriptStep.Name, testkube.ExecutionRequest{
-			Name: fmt.Sprintf("%s-%s", testName, executeScriptStep.Name),
+			Name: fmt.Sprintf("%s-%s-%s", testName, executeScriptStep.Name, rand.String(5)),
```
Comment (vsukhin) [inline internal/app/api/v1/tests.go:230]: Just in case, random there is a math random and it's not unique

**Review by vsukhin — APPROVED** [review]
looks good

**Review by jasmingacic — APPROVED** [review]

File: internal/app/api/v1/tests.go (hunk 1 above)
Comment (exu) [reply internal/app/api/v1/tests.go:230]: yeah I'm doing seed in common.go :) in rand package
